### ISSUE TITLE
Cannot clone this lesson right now. Please try again.

### ISSUE THREAD

**Issue by ettynan** [learn-co-curriculum/hello-world-ruby#79]
I had this problem with lesson 1 when I typed learn open and thought it was cleared up after my time working with kwebster (I believe that was his username), where he had me make an SSH key on my github, but the issue is happening now on lesson 2. He mentioned that IDE 3 was just released this week and this may be an issue with how it deals with previous students/people who have tried the free courses with Flatiron.

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙

**Comment by ettynan** [comment]
Hi Gabe, 

I did do 'ask a question', which I mentioned in the issue I posted. It did not resolve the problem. I had (incorrectly it seems) thought IDE 3 issues would be a 'raise an issue' we should raise since it is so tied into the functioning of the platform overall and one would not be able to move forward with IDE 3 not working. 

Is there some direct way to raise customer support to handle a continued bug issue in a more timely fashion, rather than the ask a question button? I kept getting different people with each instance and frankly, explaining the issue over and over is not efficient.

Sincerely,

Erin

**Comment by gj** [comment]
Hi @ettynan !

Sorry to be giving you a bit of a run-around, but the best way to report IDE 3 bugs is through Ask a Question. The technical coaches are trained in how to log IDE 3 issues so they get properly escalated to the engineers. At the beginning of your question, you can alert the technical coach that you've asked previous questions concerning the same issue, and they should be able to pull up a transcript of those sessions so you don't have to repeat too much.

Hope that helps!

**Comment by ettynan** [comment]
Hi Gabe,

Thank you for your response. I did those steps regarding my instances on ask a question. 

I suppose I will leave it at that and move on to other resources.

Sincerely,

Erin
